services:
  oddjob:
    build:
      context: .
      dockerfile: Dockerfile
    image: oddjob:latest
    read_only: true
    restart: on-failure:10
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./config.json:/config.json:ro
    command: ["-config", "/config.json"]
